salesforce_sfdx/main/default/objects/MX_CommonLog__c/MX_CommonLog__c.object-meta.xml
<CustomObject>
    <label>Common Log</label>
    <nameField>
        <displayFormat>Log - {000}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Common Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_sfdx/main/default/objects/MX_CommonLog__c/fields/MX_ComponentName__c.field-meta.xml
<CustomField>
    <fullName>MX_ComponentName__c</fullName>
    <label>Component Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/MX_CommonLog__c/fields/MX_ComponentType__c.field-meta.xml
<CustomField>
    <fullName>MX_ComponentType__c</fullName>
    <label>Component Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/MX_CommonLog__c/fields/MX_LoggingLevel__c.field-meta.xml
<CustomField>
    <fullName>MX_LoggingLevel__c</fullName>
    <label>Logging Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FINE</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

salesforce_sfdx/main/default/objects/MX_CommonLog__c/fields/MX_Message__c.field-meta.xml
<CustomField>
    <fullName>MX_Message__c</fullName>
    <label>Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

salesforce_sfdx/main/default/objects/MX_CommonLog__c/fields/MX_Stacktrace__c.field-meta.xml
<CustomField>
    <fullName>MX_Stacktrace__c</fullName>
    <label>Stacktrace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

salesforce_sfdx/main/default/objects/MX_LoggingConfigurations__c/MX_LoggingConfigurations__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Logging Configurations</label>
</CustomObject>

salesforce_sfdx/main/default/objects/MX_LoggingConfigurations__c/fields/MX_LoggingEnabled__c.field-meta.xml
<CustomField>
    <fullName>MX_LoggingEnabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>to enable the logging</description>
    <label>MX Logging Enabled</label>
    <type>Checkbox</type>
</CustomField>

salesforce_sfdx/main/default/objects/MX_LoggingConfigurations__c/fields/MX_LoggingLevel__c.field-meta.xml
<CustomField>
    <fullName>MX_LoggingLevel__c</fullName>
    <label>MX Logging Level</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/classes/Logger.cls
/**
* @name: Logger
* @description: abstract class for logging
* @author: Gagandeep Bansal gagandeep.bansal@salesforce.com
* @date: 04/05/2021
* @group MX Logging Framework   
*/
public abstract class Logger {

    private static final String DEFAULT_LOGGING_LEVEL_KEY   = 'Default';

    
    //to store custom settings
    private boolean isLoggingEnabled;
    private LoggingLevel defaultLoggingLevel;
    
    /*
    *    LoggingLevel    ordinal 
    *       NONE            0
    *       INTERNAL        1
    *       FINEST          2
    *       FINER           3
    *       FINE            4
    *       DEBUG           5
    *       INFO            6
    *       WARN            7
    *       ERROR           8
    */

    protected void log (LoggingLevel logLevel, String componentType, String componentName, String message, String stacktrace) {
        populateLoggingConfigurations();
        
        if (!this.isLoggingEnabled) {
            return;
        }
        
        if (LoggingLevel.NONE == this.defaultLoggingLevel) {
            return;
        }
        
        if (this.defaultLoggingLevel.ordinal() <= logLevel.ordinal()) {
            MX_CommonLog__c commonLog = createLogEvent(componentType, componentName, message, stacktrace, logLevel.name());
            publishLogEvent(commonLog);
        }   
    }
    
    private void populateLoggingConfigurations () {
        MX_LoggingConfigurations__c logConfSettings   = MX_LoggingConfigurations__c.getValues(DEFAULT_LOGGING_LEVEL_KEY);
        if (null != logConfSettings) {
            this.isLoggingEnabled                     = logConfSettings.MX_LoggingEnabled__c;
            this.defaultLoggingLevel                  = LoggingLevel.NONE;
            
            for (LoggingLevel systemLoggingLevel : LoggingLevel.values()) {
                if (systemLoggingLevel.name() == logConfSettings.MX_LoggingLevel__c) {
                    this.defaultLoggingLevel = systemLoggingLevel;
                    break;
                }
            }                         
        } 
        
    }

    protected void log (LoggingLevel logLevel, String componentType, String componentName, String message) {
        log(logLevel, componentType, componentName, message, null);
    }

    private MX_CommonLog__c createLogEvent (String componentType, String componentName, String message, String stacktrace, String loggingLevel) {
        MX_CommonLog__c commonLog = new MX_CommonLog__c (
            MX_ComponentType__c    = componentType,
            MX_ComponentName__c    = componentName,
            MX_Message__c          = message == null ? null : String.valueOf(message),
            MX_Stacktrace__c       = stacktrace == null ? null : String.valueOf(stacktrace),
            MX_LoggingLevel__c     = loggingLevel
        );
        return commonLog;
    }

    private void publishLogEvent (MX_CommonLog__c commonLog) {
        try {
            insert commonLog;
        } catch (DMLException ex) {
            System.debug ('Error while logging : ' + ex.getMessage());
        }
    }
}